// Generated by scripts/sync-nanoka-echoes.mjs. Do not edit.
export const catalogProvenance={"sources":{"characters":"https://static.nanoka.cc/ww/3.5/character.json","weapons":"https://static.nanoka.cc/ww/3.5/weapon.json","echoes":"https://static.nanoka.cc/ww/3.5/echo.json","titles":"https://api-v2.encore.moe/api/en/title"},"dataVersion":"3.5","generatedAt":"2026-07-23T10:07:56.306Z"} as const
