// Generated by scripts/sync-nanoka-echoes.mjs. Do not edit.
import type { GeneratedEchoCatalogEntry } from './catalog-types.generated'
export type { GeneratedEchoCatalogEntry }
export { catalogProvenance as echoCatalogProvenance } from './catalog-provenance.generated'
export const generatedEchoCatalog:GeneratedEchoCatalogEntry[]=[
  {
    "id": "6000077",
    "name": "Abyssal Gladius",
    "cost": 3,
    "sonatas": [
      "Midnight Veil",
      "Tidebreaking Courage",
      "Thread of Severed Fate"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000077",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32026_UI.T_IconMonsterHead_32026_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32026_UI.webp"
  },
  {
    "id": "6000078",
    "name": "Abyssal Mercator",
    "cost": 3,
    "sonatas": [
      "Frosty Resolve",
      "Eternal Radiance"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000078",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32027_UI.T_IconMonsterHead_32027_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32027_UI.webp"
  },
  {
    "id": "6000076",
    "name": "Abyssal Patricius",
    "cost": 3,
    "sonatas": [
      "Frosty Resolve",
      "Empyrean Anthem"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000076",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32025_UI.T_IconMonsterHead_32025_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32025_UI.webp"
  },
  {
    "id": "6000101",
    "name": "Aero Drake",
    "cost": 1,
    "sonatas": [
      "Tidebreaking Courage",
      "Gusts of Welkin",
      "Flaming Clawprint"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000101",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31055_UI.T_IconMonsterHead_31055_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31055_UI.webp"
  },
  {
    "id": "390070071",
    "name": "Aero Predator",
    "cost": 1,
    "sonatas": [
      "Void Thunder",
      "Sierra Gale"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070071",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_231_UI.T_IconMonsterGoods_231_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_231_UI.webp"
  },
  {
    "id": "6000095",
    "name": "Aero Prism",
    "cost": 1,
    "sonatas": [
      "Eternal Radiance",
      "Tidebreaking Courage"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000095",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31051_UI.T_IconMonsterHead_31051_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31051_UI.webp"
  },
  {
    "id": "6000205",
    "name": "Aureate Picket",
    "cost": 1,
    "sonatas": [
      "Heart of Evil's Purge"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000205",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31093_UI.T_IconMonsterHead_31093_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31093_UI.webp"
  },
  {
    "id": "6000049",
    "name": "Autopuppet Scout",
    "cost": 3,
    "sonatas": [
      "Freezing Frost",
      "Celestial Light"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000049",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_1003_UI.T_IconMonsterHead_1003_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_1003_UI.webp"
  },
  {
    "id": "390070079",
    "name": "Baby Roseshroom",
    "cost": 1,
    "sonatas": [
      "Sierra Gale",
      "Havoc Eclipse"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070079",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_301_UI.T_IconMonsterGoods_301_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_301_UI.webp"
  },
  {
    "id": "390070078",
    "name": "Baby Viridblaze Saurian",
    "cost": 1,
    "sonatas": [
      "Molten Rift",
      "Void Thunder",
      "Lingering Tunes"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070078",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_281_UI.T_IconMonsterGoods_281_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_281_UI.webp"
  },
  {
    "id": "390080005",
    "name": "Bell-Borne Geochelone",
    "cost": 4,
    "sonatas": [
      "Rejuvenating Glow",
      "Moonlit Clouds"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 3,
    "articleUrl": "https://ww.nanoka.cc/echo/390080005",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_992_UI.T_IconMonsterGoods_992_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_992_UI.webp"
  },
  {
    "id": "6000094",
    "name": "Calcified Junrock",
    "cost": 1,
    "sonatas": [
      "Empyrean Anthem",
      "Tidebreaking Courage",
      "Crown of Valor"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000094",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31050_UI.T_IconMonsterHead_31050_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31050_UI.webp"
  },
  {
    "id": "6000104",
    "name": "Capitaneus",
    "cost": 3,
    "sonatas": [
      "Eternal Radiance",
      "Gusts of Welkin",
      "Windward Pilgrimage"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000104",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32033_UI.T_IconMonsterHead_32033_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32033_UI.webp"
  },
  {
    "id": "6000046",
    "name": "Carapace",
    "cost": 3,
    "sonatas": [
      "Sierra Gale",
      "Moonlit Clouds"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000046",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_970_UI.T_IconMonsterGoods_970_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_970_UI.webp"
  },
  {
    "id": "390077025",
    "name": "Chasm Guardian",
    "cost": 3,
    "sonatas": [
      "Rejuvenating Glow",
      "Lingering Tunes"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/390077025",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_211_UI.T_IconMonsterGoods_211_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_211_UI.webp"
  },
  {
    "id": "6000072",
    "name": "Chest Mimic",
    "cost": 1,
    "sonatas": [
      "Frosty Resolve",
      "Midnight Veil",
      "Empyrean Anthem"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000072",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31048_UI.T_IconMonsterHead_31048_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31048_UI.webp"
  },
  {
    "id": "6000047",
    "name": "Chirpuff",
    "cost": 1,
    "sonatas": [
      "Sierra Gale",
      "Havoc Eclipse"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000047",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_971_UI.T_IconMonsterGoods_971_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_971_UI.webp"
  },
  {
    "id": "6000079",
    "name": "Chop Chop",
    "cost": 3,
    "sonatas": [
      "Empyrean Anthem",
      "Tidebreaking Courage",
      "Dream of the Lost"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000079",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32028_UI.T_IconMonsterHead_32028_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32028_UI.webp"
  },
  {
    "id": "6000064",
    "name": "Chop Chop: Headless",
    "cost": 1,
    "sonatas": [
      "Eternal Radiance",
      "Tidebreaking Courage"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000064",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31040_UI.T_IconMonsterHead_31040_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31040_UI.webp"
  },
  {
    "id": "6000065",
    "name": "Chop Chop: Leftless",
    "cost": 1,
    "sonatas": [
      "Frosty Resolve",
      "Tidebreaking Courage"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000065",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31041_UI.T_IconMonsterHead_31041_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31041_UI.webp"
  },
  {
    "id": "6000066",
    "name": "Chop Chop: Rightless",
    "cost": 1,
    "sonatas": [
      "Frosty Resolve",
      "Tidebreaking Courage"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000066",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31042_UI.T_IconMonsterHead_31042_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31042_UI.webp"
  },
  {
    "id": "6000051",
    "name": "Clang Bang",
    "cost": 1,
    "sonatas": [
      "Freezing Frost",
      "Celestial Light"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000051",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_1001_UI.T_IconMonsterHead_1001_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_1001_UI.webp"
  },
  {
    "id": "6000120",
    "name": "Corrosaurus",
    "cost": 3,
    "sonatas": [
      "Flaming Clawprint",
      "Flamewing's Shadow"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000120",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32044_UI.T_IconMonsterHead_32044_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32044_UI.webp"
  },
  {
    "id": "6000042",
    "name": "Crownless",
    "cost": 4,
    "sonatas": [
      "Havoc Eclipse"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000042",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_9991_UI.T_IconMonsterGoods_9991_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_9991_UI.webp"
  },
  {
    "id": "390070074",
    "name": "Cruisewing",
    "cost": 1,
    "sonatas": [
      "Celestial Light",
      "Rejuvenating Glow",
      "Moonlit Clouds"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070074",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_251_UI.T_IconMonsterGoods_251_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_251_UI.webp"
  },
  {
    "id": "6000081",
    "name": "Cuddle Wuddle",
    "cost": 3,
    "sonatas": [
      "Frosty Resolve",
      "Midnight Veil"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000081",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32030_UI.T_IconMonsterHead_32030_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32030_UI.webp"
  },
  {
    "id": "390077005",
    "name": "Cyan-Feathered Heron",
    "cost": 3,
    "sonatas": [
      "Sierra Gale",
      "Celestial Light"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/390077005",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_131_UI.T_IconMonsterGoods_131_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_131_UI.webp"
  },
  {
    "id": "6000110",
    "name": "Devotee's Flesh",
    "cost": 1,
    "sonatas": [
      "Gusts of Welkin",
      "Windward Pilgrimage",
      "Flaming Clawprint"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000110",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31061_UI.T_IconMonsterHead_31061_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31061_UI.webp"
  },
  {
    "id": "6000041",
    "name": "Diamondclaw",
    "cost": 1,
    "sonatas": [
      "Moonlit Clouds",
      "Lingering Tunes"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000041",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_987_UI.T_IconMonsterGoods_987_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_987_UI.webp"
  },
  {
    "id": "6000071",
    "name": "Diggy Duggy",
    "cost": 1,
    "sonatas": [
      "Eternal Radiance",
      "Tidebreaking Courage"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000071",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31047_UI.T_IconMonsterHead_31047_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31047_UI.webp"
  },
  {
    "id": "6000074",
    "name": "Diurnus Knight",
    "cost": 3,
    "sonatas": [
      "Eternal Radiance",
      "Tidebreaking Courage"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000074",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32023_UI.T_IconMonsterHead_32023_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32023_UI.webp"
  },
  {
    "id": "6000084",
    "name": "Dragon of Dirge",
    "cost": 4,
    "sonatas": [
      "Tidebreaking Courage"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000084",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_33013_UI.T_IconMonsterHead_33013_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_33013_UI.webp"
  },
  {
    "id": "6000053",
    "name": "Dreamless",
    "cost": 4,
    "sonatas": [
      "Havoc Eclipse"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 3,
    "articleUrl": "https://ww.nanoka.cc/echo/6000053",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_998_UI.T_IconMonsterHead_998_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_998_UI.webp"
  },
  {
    "id": "6000055",
    "name": "Dwarf Cassowary",
    "cost": 1,
    "sonatas": [
      "Sierra Gale",
      "Rejuvenating Glow"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000055",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_330_UI.T_IconMonsterHead_330_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_330_UI.webp"
  },
  {
    "id": "6000102",
    "name": "Electro Drake",
    "cost": 1,
    "sonatas": [
      "Midnight Veil",
      "Gusts of Welkin",
      "Flaming Clawprint"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000102",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31056_UI.T_IconMonsterHead_31056_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31056_UI.webp"
  },
  {
    "id": "390070053",
    "name": "Electro Predator",
    "cost": 1,
    "sonatas": [
      "Molten Rift",
      "Void Thunder"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070053",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_031_UI.T_IconMonsterGoods_031_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_031_UI.webp"
  },
  {
    "id": "390070077",
    "name": "Excarat",
    "cost": 1,
    "sonatas": [
      "Freezing Frost",
      "Havoc Eclipse"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070077",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_271_UI.T_IconMonsterGoods_271_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_271_UI.webp"
  },
  {
    "id": "6000067",
    "name": "Fae Ignis",
    "cost": 1,
    "sonatas": [
      "Eternal Radiance",
      "Midnight Veil",
      "Dream of the Lost"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000067",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31043_UI.T_IconMonsterHead_31043_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31043_UI.webp"
  },
  {
    "id": "6000060",
    "name": "Fallacy of No Return",
    "cost": 4,
    "sonatas": [
      "Rejuvenating Glow"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000060",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_350_UI.T_IconMonsterHead_350_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_350_UI.webp"
  },
  {
    "id": "6000043",
    "name": "Feilian Beringal",
    "cost": 4,
    "sonatas": [
      "Sierra Gale"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000043",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_996_UI.T_IconMonsterGoods_996_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_996_UI.webp"
  },
  {
    "id": "390070052",
    "name": "Fission Junrock",
    "cost": 1,
    "sonatas": [
      "Void Thunder",
      "Rejuvenating Glow",
      "Moonlit Clouds"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070052",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_021_UI.T_IconMonsterGoods_021_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_021_UI.webp"
  },
  {
    "id": "390077022",
    "name": "Flautist",
    "cost": 3,
    "sonatas": [
      "Void Thunder",
      "Lingering Tunes"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/390077022",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_191_UI.T_IconMonsterGoods_191_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_191_UI.webp"
  },
  {
    "id": "6000175",
    "name": "Flora Drone",
    "cost": 1,
    "sonatas": [
      "Pact of Neonlight Leap",
      "Rite of Gilded Revelation",
      "Sound of True Name",
      "Reel of Spliced Memories"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000175",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31077_UI.T_IconMonsterHead_31077_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31077_UI.webp"
  },
  {
    "id": "6000181",
    "name": "Flora Reindeer",
    "cost": 3,
    "sonatas": [
      "Rite of Gilded Revelation",
      "Reel of Spliced Memories"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000181",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32051_UI.T_IconMonsterHead_32051_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32051_UI.webp"
  },
  {
    "id": "6000215",
    "name": "Fog Lionarch",
    "cost": 3,
    "sonatas": [
      "Song of Feathered Trace",
      "Heart of Evil's Purge",
      "Lamp of Nether Road"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000215",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32067_UI.T_IconMonsterHead_32067_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32067_UI.webp"
  },
  {
    "id": "6000212",
    "name": "Fog Lionarch: Body",
    "cost": 1,
    "sonatas": [
      "Song of Feathered Trace"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000212",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31100_UI.T_IconMonsterHead_31100_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31100_UI.webp"
  },
  {
    "id": "6000213",
    "name": "Fog Lionarch: Head",
    "cost": 1,
    "sonatas": [
      "Song of Feathered Trace"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000213",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31101_UI.T_IconMonsterHead_31101_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31101_UI.webp"
  },
  {
    "id": "6000216",
    "name": "Forbidden Bastion",
    "cost": 3,
    "sonatas": [
      "Song of Feathered Trace",
      "Heart of Evil's Purge",
      "Lamp of Nether Road"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000216",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32068_UI.T_IconMonsterHead_32068_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32068_UI.webp"
  },
  {
    "id": "6000187",
    "name": "Frostbite Coleoid",
    "cost": 3,
    "sonatas": [
      "Halo of Starry Radiance",
      "Wishes of Quiet Snowfall"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000187",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32057_UI.T_IconMonsterHead_32057_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32057_UI.webp"
  },
  {
    "id": "6000063",
    "name": "Frostscourge Stalker",
    "cost": 1,
    "sonatas": [
      "Eternal Radiance",
      "Midnight Veil"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000063",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31039_UI.T_IconMonsterHead_31039_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31039_UI.webp"
  },
  {
    "id": "6000107",
    "name": "Fusion Drake",
    "cost": 1,
    "sonatas": [
      "Windward Pilgrimage",
      "Flaming Clawprint"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000107",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31058_UI.T_IconMonsterHead_31058_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31058_UI.webp"
  },
  {
    "id": "390070100",
    "name": "Fusion Dreadmane",
    "cost": 1,
    "sonatas": [
      "Molten Rift",
      "Rejuvenating Glow"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070100",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_980_UI.T_IconMonsterGoods_980_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_980_UI.webp"
  },
  {
    "id": "390077012",
    "name": "Fusion Prism",
    "cost": 1,
    "sonatas": [
      "Freezing Frost",
      "Molten Rift",
      "Lingering Tunes"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390077012",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_151_UI.T_IconMonsterGoods_151_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_151_UI.webp"
  },
  {
    "id": "390070064",
    "name": "Fusion Warrior",
    "cost": 1,
    "sonatas": [
      "Molten Rift",
      "Void Thunder",
      "Sierra Gale"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070064",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_041_UI.T_IconMonsterGoods_041_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_041_UI.webp"
  },
  {
    "id": "6000061",
    "name": "Galescourge Stalker",
    "cost": 1,
    "sonatas": [
      "Frosty Resolve",
      "Empyrean Anthem"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000061",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31037_UI.T_IconMonsterHead_31037_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31037_UI.webp"
  },
  {
    "id": "6000177",
    "name": "Geospider S4",
    "cost": 1,
    "sonatas": [
      "Pact of Neonlight Leap",
      "Halo of Starry Radiance",
      "Trailblazing Star"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000177",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31079_UI.T_IconMonsterHead_31079_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31079_UI.webp"
  },
  {
    "id": "6000103",
    "name": "Glacio Drake",
    "cost": 1,
    "sonatas": [
      "Gusts of Welkin",
      "Windward Pilgrimage"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000103",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31057_UI.T_IconMonsterHead_31057_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31057_UI.webp"
  },
  {
    "id": "6000056",
    "name": "Glacio Dreadmane",
    "cost": 3,
    "sonatas": [
      "Freezing Frost",
      "Moonlit Clouds"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000056",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_985_UI.T_IconMonsterHead_985_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_985_UI.webp"
  },
  {
    "id": "390070070",
    "name": "Glacio Predator",
    "cost": 1,
    "sonatas": [
      "Freezing Frost",
      "Celestial Light"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070070",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_101_UI.T_IconMonsterGoods_101_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_101_UI.webp"
  },
  {
    "id": "390077013",
    "name": "Glacio Prism",
    "cost": 1,
    "sonatas": [
      "Freezing Frost",
      "Havoc Eclipse",
      "Moonlit Clouds"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390077013",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_141_UI.T_IconMonsterGoods_141_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_141_UI.webp"
  },
  {
    "id": "6000195",
    "name": "Glommoth",
    "cost": 3,
    "sonatas": [
      "Trailblazing Star",
      "Wishes of Quiet Snowfall"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000195",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32061_UI.T_IconMonsterHead_32061_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32061_UI.webp"
  },
  {
    "id": "6000093",
    "name": "Golden Junrock",
    "cost": 1,
    "sonatas": [
      "Frosty Resolve",
      "Eternal Radiance",
      "Law of Harmony"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000093",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31049_UI.T_IconMonsterHead_31049_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31049_UI.webp"
  },
  {
    "id": "390070076",
    "name": "Gulpuff",
    "cost": 1,
    "sonatas": [
      "Freezing Frost",
      "Celestial Light"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070076",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_111_UI.T_IconMonsterGoods_111_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_111_UI.webp"
  },
  {
    "id": "6000109",
    "name": "Havoc Drake",
    "cost": 1,
    "sonatas": [
      "Windward Pilgrimage",
      "Flaming Clawprint",
      "Thread of Severed Fate"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000109",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31060_UI.T_IconMonsterHead_31060_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31060_UI.webp"
  },
  {
    "id": "390077033",
    "name": "Havoc Dreadmane",
    "cost": 3,
    "sonatas": [
      "Molten Rift",
      "Havoc Eclipse"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/390077033",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_984_UI.T_IconMonsterGoods_984_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_984_UI.webp"
  },
  {
    "id": "390077017",
    "name": "Havoc Prism",
    "cost": 1,
    "sonatas": [
      "Void Thunder",
      "Celestial Light",
      "Havoc Eclipse"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390077017",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_171_UI.T_IconMonsterGoods_171_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_171_UI.webp"
  },
  {
    "id": "390070065",
    "name": "Havoc Warrior",
    "cost": 1,
    "sonatas": [
      "Celestial Light",
      "Havoc Eclipse"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070065",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_051_UI.T_IconMonsterGoods_051_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_051_UI.webp"
  },
  {
    "id": "6000085",
    "name": "Hecate",
    "cost": 4,
    "sonatas": [
      "Empyrean Anthem"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 3,
    "articleUrl": "https://ww.nanoka.cc/echo/6000085",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34010_1_UI.T_IconMonsterHead_34010_1_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34010_1_UI.webp"
  },
  {
    "id": "390070105",
    "name": "Hoartoise",
    "cost": 1,
    "sonatas": [
      "Freezing Frost",
      "Celestial Light"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070105",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_969_UI.T_IconMonsterGoods_969_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_969_UI.webp"
  },
  {
    "id": "6000069",
    "name": "Hocus Pocus",
    "cost": 1,
    "sonatas": [
      "Frosty Resolve",
      "Empyrean Anthem"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000069",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31045_UI.T_IconMonsterHead_31045_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31045_UI.webp"
  },
  {
    "id": "6000040",
    "name": "Hoochief",
    "cost": 3,
    "sonatas": [
      "Sierra Gale",
      "Rejuvenating Glow"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000040",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_989_UI.T_IconMonsterGoods_989_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_989_UI.webp"
  },
  {
    "id": "6000038",
    "name": "Hooscamp",
    "cost": 1,
    "sonatas": [
      "Sierra Gale",
      "Lingering Tunes"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000038",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_988_UI.T_IconMonsterGoods_988_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_988_UI.webp"
  },
  {
    "id": "6000097",
    "name": "Hurriclaw",
    "cost": 3,
    "sonatas": [
      "Tidebreaking Courage",
      "Gusts of Welkin",
      "Crown of Valor"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000097",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32032_UI.T_IconMonsterHead_32032_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32032_UI.webp"
  },
  {
    "id": "6000189",
    "name": "Hyvatia",
    "cost": 4,
    "sonatas": [
      "Pact of Neonlight Leap",
      "Rite of Gilded Revelation"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000189",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34021_UI.T_IconMonsterHead_34021_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34021_UI.webp"
  },
  {
    "id": "6000196",
    "name": "Iceglint Dancer",
    "cost": 1,
    "sonatas": [
      "Trailblazing Star",
      "Wishes of Quiet Snowfall",
      "Reel of Spliced Memories"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000196",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31083_UI.T_IconMonsterHead_31083_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31083_UI.webp"
  },
  {
    "id": "6000052",
    "name": "Impermanence Heron",
    "cost": 4,
    "sonatas": [
      "Moonlit Clouds"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000052",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_995_UI.T_IconMonsterHead_995_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_995_UI.webp"
  },
  {
    "id": "390080007",
    "name": "Inferno Rider",
    "cost": 4,
    "sonatas": [
      "Molten Rift"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/390080007",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_321_UI.T_IconMonsterGoods_321_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_321_UI.webp"
  },
  {
    "id": "6000183",
    "name": "Ironhoof",
    "cost": 3,
    "sonatas": [
      "Pact of Neonlight Leap",
      "Wishes of Quiet Snowfall",
      "Reel of Spliced Memories"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000183",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32053_UI.T_IconMonsterHead_32053_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32053_UI.webp"
  },
  {
    "id": "6000059",
    "name": "Jué",
    "cost": 4,
    "sonatas": [
      "Celestial Light"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 3,
    "articleUrl": "https://ww.nanoka.cc/echo/6000059",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_327_UI.T_IconMonsterHead_327_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_327_UI.webp"
  },
  {
    "id": "6000112",
    "name": "Kerasaur",
    "cost": 3,
    "sonatas": [
      "Windward Pilgrimage",
      "Flaming Clawprint",
      "Flamewing's Shadow"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000112",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31062_UI.T_IconMonsterHead_31062_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31062_UI.webp"
  },
  {
    "id": "6000207",
    "name": "Kernel Puppet: Anger",
    "cost": 1,
    "sonatas": [
      "Heart of Evil's Purge"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000207",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31095_UI.T_IconMonsterHead_31095_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31095_UI.webp"
  },
  {
    "id": "6000211",
    "name": "Kernel Puppet: Fright",
    "cost": 1,
    "sonatas": [
      "Lamp of Nether Road"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000211",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31099_UI.T_IconMonsterHead_31099_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31099_UI.webp"
  },
  {
    "id": "6000210",
    "name": "Kernel Puppet: Grief",
    "cost": 1,
    "sonatas": [
      "Lamp of Nether Road"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000210",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31098_UI.T_IconMonsterHead_31098_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31098_UI.webp"
  },
  {
    "id": "6000206",
    "name": "Kernel Puppet: Joy",
    "cost": 1,
    "sonatas": [
      "Song of Feathered Trace"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000206",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31094_UI.T_IconMonsterHead_31094_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31094_UI.webp"
  },
  {
    "id": "6000209",
    "name": "Kernel Puppet: Reflection",
    "cost": 1,
    "sonatas": [
      "Heart of Evil's Purge"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000209",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31097_UI.T_IconMonsterHead_31097_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31097_UI.webp"
  },
  {
    "id": "6000208",
    "name": "Kernel Puppet: Worry",
    "cost": 1,
    "sonatas": [
      "Heart of Evil's Purge"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000208",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31096_UI.T_IconMonsterHead_31096_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31096_UI.webp"
  },
  {
    "id": "6000193",
    "name": "Kronablight",
    "cost": 3,
    "sonatas": [
      "Trailblazing Star",
      "Chromatic Foam"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000193",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32059_UI.T_IconMonsterHead_32059_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32059_UI.webp"
  },
  {
    "id": "6000098",
    "name": "La Guardia",
    "cost": 1,
    "sonatas": [
      "Midnight Veil",
      "Gusts of Welkin",
      "Flaming Clawprint"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000098",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31052_UI.T_IconMonsterHead_31052_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31052_UI.webp"
  },
  {
    "id": "6000160",
    "name": "Lady of the Sea",
    "cost": 4,
    "sonatas": [
      "Crown of Valor"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000160",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34018_UI.T_IconMonsterHead_34018_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34018_UI.webp"
  },
  {
    "id": "6000044",
    "name": "Lampylumen Myriad",
    "cost": 4,
    "sonatas": [
      "Freezing Frost"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000044",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_994_UI.T_IconMonsterGoods_994_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_994_UI.webp"
  },
  {
    "id": "6000054",
    "name": "Lava Larva",
    "cost": 1,
    "sonatas": [
      "Molten Rift",
      "Lingering Tunes"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000054",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_326_UI.T_IconMonsterHead_326_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_326_UI.webp"
  },
  {
    "id": "6000058",
    "name": "Lightcrusher",
    "cost": 3,
    "sonatas": [
      "Celestial Light"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000058",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_328_UI.T_IconMonsterHead_328_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_328_UI.webp"
  },
  {
    "id": "6000114",
    "name": "Lioness of Glory",
    "cost": 4,
    "sonatas": [
      "Flaming Clawprint"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000114",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_33022_UI.T_IconMonsterHead_33022_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_33022_UI.webp"
  },
  {
    "id": "6000082",
    "name": "Lorelei",
    "cost": 4,
    "sonatas": [
      "Midnight Veil"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000082",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_33011_UI.T_IconMonsterHead_33011_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_33011_UI.webp"
  },
  {
    "id": "6000070",
    "name": "Lottie Lost",
    "cost": 1,
    "sonatas": [
      "Frosty Resolve",
      "Tidebreaking Courage"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000070",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31046_UI.T_IconMonsterHead_31046_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31046_UI.webp"
  },
  {
    "id": "6000057",
    "name": "Lumiscale Construct",
    "cost": 3,
    "sonatas": [
      "Freezing Frost",
      "Void Thunder"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000057",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_329_UI.T_IconMonsterHead_329_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_329_UI.webp"
  },
  {
    "id": "6000048",
    "name": "Mech Abomination",
    "cost": 4,
    "sonatas": [
      "Lingering Tunes"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000048",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_993_UI.T_IconMonsterHead_993_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_993_UI.webp"
  },
  {
    "id": "6000176",
    "name": "Mining Drone",
    "cost": 1,
    "sonatas": [
      "Halo of Starry Radiance",
      "Rite of Gilded Revelation",
      "Sound of True Name",
      "Reel of Spliced Memories"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000176",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31078_UI.T_IconMonsterHead_31078_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31078_UI.webp"
  },
  {
    "id": "6000182",
    "name": "Mining Reindeer",
    "cost": 3,
    "sonatas": [
      "Pact of Neonlight Leap",
      "Reel of Spliced Memories"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000182",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32052_UI.T_IconMonsterHead_32052_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32052_UI.webp"
  },
  {
    "id": "6000045",
    "name": "Mourning Aix",
    "cost": 4,
    "sonatas": [
      "Celestial Light"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000045",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_997_UI.T_IconMonsterGoods_997_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_997_UI.webp"
  },
  {
    "id": "6000217",
    "name": "Myriad Snare: Rustfire Chassis",
    "cost": 4,
    "sonatas": [
      "Heart of Evil's Purge",
      "Lamp of Nether Road"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000217",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34030_UI.T_IconMonsterHead_34030_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34030_UI.webp"
  },
  {
    "id": "6000192",
    "name": "Nameless Explorer",
    "cost": 4,
    "sonatas": [
      "Sound of True Name",
      "Reel of Spliced Memories"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000192",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34026_UI.T_IconMonsterHead_34026_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34026_UI.webp"
  },
  {
    "id": "6000164",
    "name": "Nightmare: Aero Predator",
    "cost": 1,
    "sonatas": [
      "Crown of Valor"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000164",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31066_UI.T_IconMonsterHead_31066_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31066_UI.webp"
  },
  {
    "id": "6000170",
    "name": "Nightmare: Baby Roseshroom",
    "cost": 1,
    "sonatas": [
      "Flamewing's Shadow"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000170",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31073_UI.T_IconMonsterHead_31073_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31073_UI.webp"
  },
  {
    "id": "6000169",
    "name": "Nightmare: Baby Viridblaze Saurian",
    "cost": 1,
    "sonatas": [
      "Flamewing's Shadow"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000169",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31072_UI.T_IconMonsterHead_31072_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31072_UI.webp"
  },
  {
    "id": "6000166",
    "name": "Nightmare: Chirpuff",
    "cost": 1,
    "sonatas": [
      "Law of Harmony"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000166",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31068_UI.T_IconMonsterHead_31068_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31068_UI.webp"
  },
  {
    "id": "6000090",
    "name": "Nightmare: Crownless",
    "cost": 4,
    "sonatas": [
      "Havoc Eclipse"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000090",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_YZ_33018_UI.T_IconMonsterHead_YZ_33018_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_YZ_33018_UI.webp"
  },
  {
    "id": "6000162",
    "name": "Nightmare: Cyan-Feathered Heron",
    "cost": 3,
    "sonatas": [
      "Law of Harmony"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000162",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32046_UI.T_IconMonsterHead_32046_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32046_UI.webp"
  },
  {
    "id": "6000172",
    "name": "Nightmare: Dwarf Cassowary",
    "cost": 1,
    "sonatas": [
      "Thread of Severed Fate"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000172",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31076_UI.T_IconMonsterHead_31076_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31076_UI.webp"
  },
  {
    "id": "6000163",
    "name": "Nightmare: Electro Predator",
    "cost": 1,
    "sonatas": [
      "Crown of Valor"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000163",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31065_UI.T_IconMonsterHead_31065_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31065_UI.webp"
  },
  {
    "id": "6000086",
    "name": "Nightmare: Feilian Beringal",
    "cost": 4,
    "sonatas": [
      "Sierra Gale"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000086",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_YZ_33014_UI.T_IconMonsterHead_YZ_33014_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_YZ_33014_UI.webp"
  },
  {
    "id": "6000118",
    "name": "Nightmare: Glacio Predator",
    "cost": 1,
    "sonatas": [
      "Dream of the Lost"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000118",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31064_UI.T_IconMonsterHead_31064_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31064_UI.webp"
  },
  {
    "id": "6000165",
    "name": "Nightmare: Gulpuff",
    "cost": 1,
    "sonatas": [
      "Law of Harmony"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000165",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31067_UI.T_IconMonsterHead_31067_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31067_UI.webp"
  },
  {
    "id": "6000117",
    "name": "Nightmare: Havoc Warrior",
    "cost": 1,
    "sonatas": [
      "Dream of the Lost"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000117",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31063_UI.T_IconMonsterHead_31063_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31063_UI.webp"
  },
  {
    "id": "6000115",
    "name": "Nightmare: Hecate",
    "cost": 4,
    "sonatas": [
      "Dream of the Lost"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 3,
    "articleUrl": "https://ww.nanoka.cc/echo/6000115",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34016_UI.T_IconMonsterHead_34016_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34016_UI.webp"
  },
  {
    "id": "6000087",
    "name": "Nightmare: Impermanence Heron",
    "cost": 4,
    "sonatas": [
      "Midnight Veil"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000087",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_YZ_33015_UI.T_IconMonsterHead_YZ_33015_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_YZ_33015_UI.webp"
  },
  {
    "id": "6000091",
    "name": "Nightmare: Inferno Rider",
    "cost": 4,
    "sonatas": [
      "Molten Rift"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000091",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_YZ_33019_UI.T_IconMonsterHead_YZ_33019_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_YZ_33019_UI.webp"
  },
  {
    "id": "6000113",
    "name": "Nightmare: Kelpie",
    "cost": 4,
    "sonatas": [
      "Gusts of Welkin",
      "Windward Pilgrimage"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000113",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_33021_UI.T_IconMonsterHead_33021_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_33021_UI.webp"
  },
  {
    "id": "6000105",
    "name": "Nightmare: Lampylumen Myriad",
    "cost": 4,
    "sonatas": [
      "Frosty Resolve",
      "Empyrean Anthem"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000105",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34013_UI.T_IconMonsterHead_34013_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34013_UI.webp"
  },
  {
    "id": "6000092",
    "name": "Nightmare: Mourning Aix",
    "cost": 4,
    "sonatas": [
      "Eternal Radiance"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000092",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_YZ_33020_UI.T_IconMonsterHead_YZ_33020_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_YZ_33020_UI.webp"
  },
  {
    "id": "6000173",
    "name": "Nightmare: Roseshroom",
    "cost": 3,
    "sonatas": [
      "Thread of Severed Fate"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000173",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32048_UI.T_IconMonsterHead_32048_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32048_UI.webp"
  },
  {
    "id": "6000119",
    "name": "Nightmare: Tambourinist",
    "cost": 3,
    "sonatas": [
      "Dream of the Lost"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000119",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32043_UI.T_IconMonsterHead_32043_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32043_UI.webp"
  },
  {
    "id": "6000089",
    "name": "Nightmare: Tempest Mephis",
    "cost": 4,
    "sonatas": [
      "Void Thunder",
      "Empyrean Anthem"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000089",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_YZ_33017_UI.T_IconMonsterHead_YZ_33017_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_YZ_33017_UI.webp"
  },
  {
    "id": "6000088",
    "name": "Nightmare: Thundering Mephis",
    "cost": 4,
    "sonatas": [
      "Void Thunder"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000088",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_YZ_33016_UI.T_IconMonsterHead_YZ_33016_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_YZ_33016_UI.webp"
  },
  {
    "id": "6000171",
    "name": "Nightmare: Tick Tack",
    "cost": 1,
    "sonatas": [
      "Thread of Severed Fate"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000171",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31075_UI.T_IconMonsterHead_31075_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31075_UI.webp"
  },
  {
    "id": "6000161",
    "name": "Nightmare: Violet-Feathered Heron",
    "cost": 3,
    "sonatas": [
      "Crown of Valor"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000161",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32045_UI.T_IconMonsterHead_32045_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32045_UI.webp"
  },
  {
    "id": "6000168",
    "name": "Nightmare: Viridblaze Saurian",
    "cost": 3,
    "sonatas": [
      "Flamewing's Shadow"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000168",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32047_UI.T_IconMonsterHead_32047_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32047_UI.webp"
  },
  {
    "id": "6000068",
    "name": "Nimbus Wraith",
    "cost": 1,
    "sonatas": [
      "Midnight Veil",
      "Empyrean Anthem",
      "Flamewing's Shadow"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000068",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31044_UI.T_IconMonsterHead_31044_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31044_UI.webp"
  },
  {
    "id": "6000075",
    "name": "Nocturnus Knight",
    "cost": 3,
    "sonatas": [
      "Midnight Veil",
      "Empyrean Anthem"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000075",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32024_UI.T_IconMonsterHead_32024_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32024_UI.webp"
  },
  {
    "id": "6000111",
    "name": "Pilgrim's Shell",
    "cost": 3,
    "sonatas": [
      "Windward Pilgrimage",
      "Flaming Clawprint"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000111",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32034_UI.T_IconMonsterHead_32034_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32034_UI.webp"
  },
  {
    "id": "6000203",
    "name": "Porcelain Picket",
    "cost": 1,
    "sonatas": [
      "Lamp of Nether Road"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000203",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31091_UI.T_IconMonsterHead_31091_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31091_UI.webp"
  },
  {
    "id": "6000073",
    "name": "Questless Knight",
    "cost": 3,
    "sonatas": [
      "Frosty Resolve",
      "Midnight Veil"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000073",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32022_UI.T_IconMonsterHead_32022_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32022_UI.webp"
  },
  {
    "id": "6000096",
    "name": "Rage Against the Statue",
    "cost": 3,
    "sonatas": [
      "Eternal Radiance",
      "Gusts of Welkin",
      "Law of Harmony"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000096",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32031_UI.T_IconMonsterHead_32031_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32031_UI.webp"
  },
  {
    "id": "6000190",
    "name": "Reactor Husk",
    "cost": 4,
    "sonatas": [
      "Halo of Starry Radiance",
      "Chromatic Foam"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000190",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34022_UI.T_IconMonsterHead_34022_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34022_UI.webp"
  },
  {
    "id": "6000201",
    "name": "Reminiscence - Nightmare: Adam Smasher",
    "cost": 4,
    "sonatas": [
      "Shadow of Shattered Dreams"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000201",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34029_1_UI.T_IconMonsterHead_34029_1_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34029_1_UI.webp"
  },
  {
    "id": "6000200",
    "name": "Reminiscence: Denia",
    "cost": 4,
    "sonatas": [
      "Chromatic Foam"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 3,
    "articleUrl": "https://ww.nanoka.cc/echo/6000200",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34028_1_UI.T_IconMonsterHead_34028_1_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34028_1_UI.webp"
  },
  {
    "id": "6000116",
    "name": "Reminiscence: Fenrico",
    "cost": 4,
    "sonatas": [
      "Dream of the Lost",
      "Law of Harmony"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000116",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34015_2_UI.T_IconMonsterHead_34015_2_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34015_2_UI.webp"
  },
  {
    "id": "6000106",
    "name": "Reminiscence: Fleurdelys",
    "cost": 4,
    "sonatas": [
      "Gusts of Welkin",
      "Windward Pilgrimage"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 3,
    "articleUrl": "https://ww.nanoka.cc/echo/6000106",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34012_1_UI.T_IconMonsterHead_34012_1_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34012_1_UI.webp"
  },
  {
    "id": "6000194",
    "name": "Reminiscence: Kronaclaw",
    "cost": 3,
    "sonatas": [
      "Trailblazing Star",
      "Chromatic Foam"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000194",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32060_UI.T_IconMonsterHead_32060_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32060_UI.webp"
  },
  {
    "id": "6000167",
    "name": "Reminiscence: Threnodian - Leviathan",
    "cost": 4,
    "sonatas": [
      "Flamewing's Shadow",
      "Thread of Severed Fate"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 3,
    "articleUrl": "https://ww.nanoka.cc/echo/6000167",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34020_1_UI.T_IconMonsterHead_34020_1_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34020_1_UI.webp"
  },
  {
    "id": "6000199",
    "name": "Reminiscence: Threnodian - Voidborne Construct",
    "cost": 4,
    "sonatas": [
      "Wishes of Quiet Snowfall"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 3,
    "articleUrl": "https://ww.nanoka.cc/echo/6000199",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34027_UI.T_IconMonsterHead_34027_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34027_UI.webp"
  },
  {
    "id": "390077024",
    "name": "Rocksteady Guardian",
    "cost": 3,
    "sonatas": [
      "Celestial Light",
      "Rejuvenating Glow"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/390077024",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_241_UI.T_IconMonsterGoods_241_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_241_UI.webp"
  },
  {
    "id": "390077029",
    "name": "Roseshroom",
    "cost": 3,
    "sonatas": [
      "Freezing Frost",
      "Havoc Eclipse"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/390077029",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_311_UI.T_IconMonsterGoods_311_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_311_UI.webp"
  },
  {
    "id": "6000186",
    "name": "Sabercat Prowler",
    "cost": 3,
    "sonatas": [
      "Pact of Neonlight Leap",
      "Halo of Starry Radiance",
      "Sound of True Name"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000186",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32056_UI.T_IconMonsterHead_32056_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32056_UI.webp"
  },
  {
    "id": "6000185",
    "name": "Sabercat Reaver",
    "cost": 3,
    "sonatas": [
      "Pact of Neonlight Leap",
      "Halo of Starry Radiance",
      "Sound of True Name"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000185",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32055_UI.T_IconMonsterHead_32055_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32055_UI.webp"
  },
  {
    "id": "390070075",
    "name": "Sabyr Boar",
    "cost": 1,
    "sonatas": [
      "Freezing Frost",
      "Sierra Gale",
      "Moonlit Clouds"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070075",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_261_UI.T_IconMonsterGoods_261_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_261_UI.webp"
  },
  {
    "id": "6000100",
    "name": "Sacerdos",
    "cost": 1,
    "sonatas": [
      "Gusts of Welkin",
      "Windward Pilgrimage"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000100",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31054_UI.T_IconMonsterHead_31054_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31054_UI.webp"
  },
  {
    "id": "6000099",
    "name": "Sagittario",
    "cost": 1,
    "sonatas": [
      "Eternal Radiance",
      "Gusts of Welkin",
      "Flaming Clawprint"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000099",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31053_UI.T_IconMonsterHead_31053_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31053_UI.webp"
  },
  {
    "id": "6000083",
    "name": "Sentry Construct",
    "cost": 4,
    "sonatas": [
      "Frosty Resolve"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000083",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_33012_UI.T_IconMonsterHead_33012_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_33012_UI.webp"
  },
  {
    "id": "6000197",
    "name": "Shadow Stepper",
    "cost": 1,
    "sonatas": [
      "Trailblazing Star",
      "Chromatic Foam",
      "Wishes of Quiet Snowfall"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000197",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31084_UI.T_IconMonsterHead_31084_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31084_UI.webp"
  },
  {
    "id": "6000191",
    "name": "Sigillum",
    "cost": 4,
    "sonatas": [
      "Trailblazing Star"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 3,
    "articleUrl": "https://ww.nanoka.cc/echo/6000191",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34025_0_UI.T_IconMonsterHead_34025_0_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34025_0_UI.webp"
  },
  {
    "id": "6000202",
    "name": "Smiter",
    "cost": 1,
    "sonatas": [
      "Song of Feathered Trace"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000202",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31090_UI.T_IconMonsterHead_31090_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31090_UI.webp"
  },
  {
    "id": "6000214",
    "name": "Smolder",
    "cost": 1,
    "sonatas": [
      "Song of Feathered Trace"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000214",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31102_UI.T_IconMonsterHead_31102_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31102_UI.webp"
  },
  {
    "id": "390070066",
    "name": "Snip Snap",
    "cost": 1,
    "sonatas": [
      "Molten Rift",
      "Rejuvenating Glow",
      "Lingering Tunes"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070066",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_061_UI.T_IconMonsterGoods_061_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_061_UI.webp"
  },
  {
    "id": "6000184",
    "name": "Spacetrek Explorer",
    "cost": 3,
    "sonatas": [
      "Halo of Starry Radiance",
      "Chromatic Foam",
      "Sound of True Name"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000184",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32054_UI.T_IconMonsterHead_32054_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32054_UI.webp"
  },
  {
    "id": "390077038",
    "name": "Spearback",
    "cost": 3,
    "sonatas": [
      "Moonlit Clouds",
      "Lingering Tunes"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/390077038",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_986_UI.T_IconMonsterGoods_986_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_986_UI.webp"
  },
  {
    "id": "6000108",
    "name": "Spectro Drake",
    "cost": 1,
    "sonatas": [
      "Windward Pilgrimage",
      "Flaming Clawprint"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000108",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31059_UI.T_IconMonsterHead_31059_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31059_UI.webp"
  },
  {
    "id": "390077016",
    "name": "Spectro Prism",
    "cost": 1,
    "sonatas": [
      "Molten Rift",
      "Void Thunder",
      "Celestial Light"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390077016",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_161_UI.T_IconMonsterGoods_161_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_161_UI.webp"
  },
  {
    "id": "6000204",
    "name": "Stone Picket",
    "cost": 1,
    "sonatas": [
      "Lamp of Nether Road"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000204",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31092_UI.T_IconMonsterHead_31092_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31092_UI.webp"
  },
  {
    "id": "390077021",
    "name": "Stonewall Bracer",
    "cost": 3,
    "sonatas": [
      "Rejuvenating Glow",
      "Moonlit Clouds"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/390077021",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_181_UI.T_IconMonsterGoods_181_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_181_UI.webp"
  },
  {
    "id": "390077023",
    "name": "Tambourinist",
    "cost": 3,
    "sonatas": [
      "Freezing Frost",
      "Havoc Eclipse"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/390077023",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_201_UI.T_IconMonsterGoods_201_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_201_UI.webp"
  },
  {
    "id": "6000039",
    "name": "Tempest Mephis",
    "cost": 4,
    "sonatas": [
      "Void Thunder"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000039",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_221_UI.T_IconMonsterGoods_221_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_221_UI.webp"
  },
  {
    "id": "6000121",
    "name": "The False Sovereign",
    "cost": 4,
    "sonatas": [
      "Crown of Valor"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/6000121",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34017_UI.T_IconMonsterHead_34017_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34017_UI.webp"
  },
  {
    "id": "6000218",
    "name": "Thousand-Puppet Pavilion",
    "cost": 4,
    "sonatas": [
      "Song of Feathered Trace"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 3,
    "articleUrl": "https://ww.nanoka.cc/echo/6000218",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34031_UI.T_IconMonsterHead_34031_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34031_UI.webp"
  },
  {
    "id": "390080003",
    "name": "Thundering Mephis",
    "cost": 4,
    "sonatas": [
      "Void Thunder"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 2,
    "articleUrl": "https://ww.nanoka.cc/echo/390080003",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_222_UI.T_IconMonsterGoods_222_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_222_UI.webp"
  },
  {
    "id": "390070069",
    "name": "Tick Tack",
    "cost": 1,
    "sonatas": [
      "Havoc Eclipse",
      "Rejuvenating Glow",
      "Lingering Tunes"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070069",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_091_UI.T_IconMonsterGoods_091_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_091_UI.webp"
  },
  {
    "id": "6000050",
    "name": "Traffic Illuminator",
    "cost": 1,
    "sonatas": [
      "Molten Rift",
      "Void Thunder",
      "Sierra Gale"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000050",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_1000_UI.T_IconMonsterHead_1000_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_1000_UI.webp"
  },
  {
    "id": "6000174",
    "name": "Tremor Warrior",
    "cost": 1,
    "sonatas": [
      "Halo of Starry Radiance",
      "Chromatic Foam",
      "Wishes of Quiet Snowfall"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000174",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31074_UI.T_IconMonsterHead_31074_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31074_UI.webp"
  },
  {
    "id": "6000180",
    "name": "Twin Nova: Collapsar Blade",
    "cost": 3,
    "sonatas": [
      "Rite of Gilded Revelation",
      "Trailblazing Star",
      "Sound of True Name"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000180",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32050_UI.T_IconMonsterHead_32050_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32050_UI.webp"
  },
  {
    "id": "6000179",
    "name": "Twin Nova: Nebulous Cannon",
    "cost": 3,
    "sonatas": [
      "Rite of Gilded Revelation",
      "Chromatic Foam"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000179",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32049_UI.T_IconMonsterHead_32049_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32049_UI.webp"
  },
  {
    "id": "390070051",
    "name": "Vanguard Junrock",
    "cost": 1,
    "sonatas": [
      "Void Thunder",
      "Rejuvenating Glow",
      "Lingering Tunes"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070051",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_011_UI.T_IconMonsterGoods_011_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_011_UI.webp"
  },
  {
    "id": "390077004",
    "name": "Violet-Feathered Heron",
    "cost": 3,
    "sonatas": [
      "Molten Rift",
      "Void Thunder"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/390077004",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_121_UI.T_IconMonsterGoods_121_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_121_UI.webp"
  },
  {
    "id": "390077028",
    "name": "Viridblaze Saurian",
    "cost": 3,
    "sonatas": [
      "Molten Rift",
      "Moonlit Clouds"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/390077028",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_291_UI.T_IconMonsterGoods_291_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_291_UI.webp"
  },
  {
    "id": "6000080",
    "name": "Vitreum Dancer",
    "cost": 3,
    "sonatas": [
      "Eternal Radiance",
      "Empyrean Anthem"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000080",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32029_UI.T_IconMonsterHead_32029_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32029_UI.webp"
  },
  {
    "id": "6000198",
    "name": "Voidwing Moth",
    "cost": 3,
    "sonatas": [
      "Reel of Spliced Memories"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000198",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32066_UI.T_IconMonsterHead_32066_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32066_UI.webp"
  },
  {
    "id": "6000062",
    "name": "Voltscourge Stalker",
    "cost": 1,
    "sonatas": [
      "Midnight Veil",
      "Empyrean Anthem"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000062",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31038_UI.T_IconMonsterHead_31038_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31038_UI.webp"
  },
  {
    "id": "390070068",
    "name": "Whiff Whaff",
    "cost": 1,
    "sonatas": [
      "Sierra Gale",
      "Rejuvenating Glow",
      "Moonlit Clouds"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070068",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_081_UI.T_IconMonsterGoods_081_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_081_UI.webp"
  },
  {
    "id": "6000188",
    "name": "Windlash Coleoid",
    "cost": 3,
    "sonatas": [
      "Rite of Gilded Revelation",
      "Wishes of Quiet Snowfall"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 1,
    "articleUrl": "https://ww.nanoka.cc/echo/6000188",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32058_UI.T_IconMonsterHead_32058_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_32058_UI.webp"
  },
  {
    "id": "390070067",
    "name": "Zig Zag",
    "cost": 1,
    "sonatas": [
      "Celestial Light",
      "Moonlit Clouds",
      "Lingering Tunes"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/390070067",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_071_UI.T_IconMonsterGoods_071_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterGoods/T_IconMonsterGoods_071_UI.webp"
  },
  {
    "id": "6000178",
    "name": "Zip Zap",
    "cost": 1,
    "sonatas": [
      "Pact of Neonlight Leap",
      "Rite of Gilded Revelation",
      "Chromatic Foam",
      "Sound of True Name"
    ],
    "rarities": [
      2,
      3,
      4,
      5
    ],
    "intensity": 0,
    "articleUrl": "https://ww.nanoka.cc/echo/6000178",
    "iconPath": "/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31082_UI.T_IconMonsterHead_31082_UI",
    "iconSourceUrl": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_31082_UI.webp"
  }
]
