// Generated by scripts/sync-nanoka-echoes.mjs. Do not edit.
import type { GeneratedSonataCatalogEntry } from './catalog-types.generated'
export const generatedSonataCatalog:GeneratedSonataCatalogEntry[]=[
  {
    "id": "1",
    "name": "Freezing Frost",
    "echoCount": 14,
    "effects": [
      {
        "pieces": 2,
        "description": "Glacio DMG + 10%."
      },
      {
        "pieces": 5,
        "description": "Glacio DMG + 10% after releasing Basic Attack or Heavy Attack. This effect stacks up to 3 times, each stack lasts 15s."
      }
    ]
  },
  {
    "id": "2",
    "name": "Molten Rift",
    "echoCount": 14,
    "effects": [
      {
        "pieces": 2,
        "description": "Fusion DMG + 10%."
      },
      {
        "pieces": 5,
        "description": "Fusion DMG + 30% for 15s after releasing Resonance Skill."
      }
    ]
  },
  {
    "id": "3",
    "name": "Void Thunder",
    "echoCount": 16,
    "effects": [
      {
        "pieces": 2,
        "description": "Electro DMG + 10%."
      },
      {
        "pieces": 5,
        "description": "Electro DMG + 15% after releasing Heavy Attack or Resonance Skill. This effect stacks up to 2 times, each stack lasts 15s."
      }
    ]
  },
  {
    "id": "4",
    "name": "Sierra Gale",
    "echoCount": 14,
    "effects": [
      {
        "pieces": 2,
        "description": "Aero DMG + 10%."
      },
      {
        "pieces": 5,
        "description": "Aero DMG + 30% for 15s after releasing Intro Skill."
      }
    ]
  },
  {
    "id": "5",
    "name": "Celestial Light",
    "echoCount": 15,
    "effects": [
      {
        "pieces": 2,
        "description": "Spectro DMG + 10%."
      },
      {
        "pieces": 5,
        "description": "Spectro DMG + 30% for 15s after releasing Intro Skill."
      }
    ]
  },
  {
    "id": "6",
    "name": "Havoc Eclipse",
    "echoCount": 13,
    "effects": [
      {
        "pieces": 2,
        "description": "Havoc DMG + 10%."
      },
      {
        "pieces": 5,
        "description": "Havoc DMG + 7.5% after releasing Basic Attack or Heavy Attack. This effect stacks up to 4 times, each stack lasts 15s."
      }
    ]
  },
  {
    "id": "7",
    "name": "Rejuvenating Glow",
    "echoCount": 14,
    "effects": [
      {
        "pieces": 2,
        "description": "Healing Bonus + 10%."
      },
      {
        "pieces": 5,
        "description": "Increases the ATK of all party members by 15% for 30s upon healing allies."
      }
    ]
  },
  {
    "id": "8",
    "name": "Moonlit Clouds",
    "echoCount": 14,
    "effects": [
      {
        "pieces": 2,
        "description": "Energy Regen + 10%."
      },
      {
        "pieces": 5,
        "description": "Upon using Outro Skill, increases the ATK of the next Resonator by 22.5% for 15s."
      }
    ]
  },
  {
    "id": "9",
    "name": "Lingering Tunes",
    "echoCount": 13,
    "effects": [
      {
        "pieces": 2,
        "description": "ATK +10%"
      },
      {
        "pieces": 5,
        "description": "While on the field, ATK increases by 5% every 1.5s. This effect stacks up to 4 times. Outro Skill DMG + 60%."
      }
    ]
  },
  {
    "id": "10",
    "name": "Frosty Resolve",
    "echoCount": 13,
    "effects": [
      {
        "pieces": 2,
        "description": "Resonance Skill DMG + 12%"
      },
      {
        "pieces": 5,
        "description": "Casting Resonance Skill grants 22.5% Glacio DMG Bonus for 15s and casting Resonance Liberation increases Resonance Skill DMG by 18%, lasting for 5s. This effect stacks up to 2 times."
      }
    ]
  },
  {
    "id": "11",
    "name": "Eternal Radiance",
    "echoCount": 13,
    "effects": [
      {
        "pieces": 2,
        "description": "Spectro DMG + 10%"
      },
      {
        "pieces": 5,
        "description": "Inflicting Spectro Frazzle on enemies increases Crit. Rate by 20% for 15s. Attacking enemies inflicted with 10 stacks of Spectro Frazzle grants 15% Spectro DMG Bonus for 15s."
      }
    ]
  },
  {
    "id": "12",
    "name": "Midnight Veil",
    "echoCount": 13,
    "effects": [
      {
        "pieces": 2,
        "description": "Havoc DMG + 10%"
      },
      {
        "pieces": 5,
        "description": "When Outro Skill is triggered, deal additional 480% Havoc DMG to surrounding enemies, considered Outro Skill DMG, and grant the incoming Resonator 15% Havoc DMG Bonus for 15s."
      }
    ]
  },
  {
    "id": "13",
    "name": "Empyrean Anthem",
    "echoCount": 13,
    "effects": [
      {
        "pieces": 2,
        "description": "Energy Regen + 10%"
      },
      {
        "pieces": 5,
        "description": "Increase the Resonator's Coordinated Attack DMG by 80%. Upon a critical hit of Coordinated Attack, increase the active Resonator's ATK by 20% for 4s."
      }
    ]
  },
  {
    "id": "14",
    "name": "Tidebreaking Courage",
    "echoCount": 13,
    "effects": [
      {
        "pieces": 2,
        "description": "Energy Regen + 10%"
      },
      {
        "pieces": 5,
        "description": "Increase the Resonator's ATK by 15%. Reaching 250% Energy Regen increases all Attribute DMG by 30% for the Resonator."
      }
    ]
  },
  {
    "id": "16",
    "name": "Gusts of Welkin",
    "echoCount": 12,
    "effects": [
      {
        "pieces": 2,
        "description": "Aero DMG + 10%"
      },
      {
        "pieces": 5,
        "description": "Inflicting Aero Erosion upon enemies increases Aero DMG for all Resonators in the team by 15%, and for the Resonator triggering this effect by an additional 15%, lasting for 20s."
      }
    ]
  },
  {
    "id": "17",
    "name": "Windward Pilgrimage",
    "echoCount": 11,
    "effects": [
      {
        "pieces": 2,
        "description": "Aero DMG + 10%"
      },
      {
        "pieces": 5,
        "description": "Hitting a target with Aero Erosion increases Crit. Rate by 10% and grants 30% Aero DMG Bonus, lasting for 10s."
      }
    ]
  },
  {
    "id": "18",
    "name": "Flaming Clawprint",
    "echoCount": 12,
    "effects": [
      {
        "pieces": 2,
        "description": "Fusion DMG + 10%"
      },
      {
        "pieces": 5,
        "description": "Casting Resonance Liberation grants all Resonators in the team 15% Fusion DMG Bonus and the caster 20% Resonance Liberation DMG Bonus, lasting for 35s."
      }
    ]
  },
  {
    "id": "19",
    "name": "Dream of the Lost",
    "echoCount": 7,
    "effects": [
      {
        "pieces": 3,
        "description": "Holding 0 Resonance Energy increases Crit. Rate by 20% and grants 35% Echo Skill DMG Bonus."
      }
    ]
  },
  {
    "id": "20",
    "name": "Crown of Valor",
    "echoCount": 7,
    "effects": [
      {
        "pieces": 3,
        "description": "Upon gaining a Shield, increase the Resonator's ATK by 6% and Crit. DMG by 4% for 4s. This effect can be triggered once every 0.5s and stacks up to 5 times."
      }
    ]
  },
  {
    "id": "21",
    "name": "Law of Harmony",
    "echoCount": 6,
    "effects": [
      {
        "pieces": 3,
        "description": "Casting Echo Skill grants 30% Heavy Attack DMG Bonus to the caster for 4s.\nAdditionally, all Resonators in the team gain 4% Echo Skill DMG Bonus for 30s, stacking up to 4 times. Echoes of the same name can only trigger this effect once. The record of Echo triggering this effect is cleared along with this effect. At 4 stacks, casting Echo Skill again resets the duration of this effect."
      }
    ]
  },
  {
    "id": "22",
    "name": "Flamewing's Shadow",
    "echoCount": 7,
    "effects": [
      {
        "pieces": 3,
        "description": "Dealing Echo Skill DMG increases Heavy Attack Crit. Rate by 20% for 6s. Dealing Heavy Attack DMG increases Echo Skill Crit. Rate by 20% for 6s. While both effects are active, gain 16% Fusion DMG Bonus."
      }
    ]
  },
  {
    "id": "23",
    "name": "Thread of Severed Fate",
    "echoCount": 6,
    "effects": [
      {
        "pieces": 3,
        "description": "Inflicting Havoc Bane increases the Resonator's ATK by 20% and grants 30% Resonance Liberation DMG Bonus for 5s."
      }
    ]
  },
  {
    "id": "24",
    "name": "Pact of Neonlight Leap",
    "echoCount": 8,
    "effects": [
      {
        "pieces": 2,
        "description": "Spectro DMG + 10%"
      },
      {
        "pieces": 5,
        "description": "Casting Outro Skill increases the ATK of the incoming Resonator who casts Intro Skill by 15%. Each point of Tune Break Boost the incoming Resonator has additionally increases their ATK by 0.3%, up to 15%. This effect lasts for 15s, or until the Resonator is switched out."
      }
    ]
  },
  {
    "id": "25",
    "name": "Halo of Starry Radiance",
    "echoCount": 8,
    "effects": [
      {
        "pieces": 2,
        "description": "Healing Bonus + 10%."
      },
      {
        "pieces": 5,
        "description": "When healing a Resonator in the team, every 1% of Off-Tune Buildup Rate grants a 0.2% ATK increase to all Resonators in the team for 4s, up to 25%. Effects of the same name cannot be stacked."
      }
    ]
  },
  {
    "id": "26",
    "name": "Rite of Gilded Revelation",
    "echoCount": 8,
    "effects": [
      {
        "pieces": 2,
        "description": "Spectro DMG + 10%"
      },
      {
        "pieces": 5,
        "description": "Dealing Basic Attack DMG increases Spectro DMG by 10% for 5s, stacking up to 3 times. With 3 stacks, casting Resonance Liberation grants 40% Basic Attack DMG Bonus."
      }
    ]
  },
  {
    "id": "27",
    "name": "Trailblazing Star",
    "echoCount": 8,
    "effects": [
      {
        "pieces": 2,
        "description": "Fusion DMG + 10%"
      },
      {
        "pieces": 5,
        "description": "Inflicting Fusion Burst or Tune Rupture - Shifting increases the Resonator's Crit. Rate by 20% and grants 20% Fusion DMG Bonus for 8s."
      }
    ]
  },
  {
    "id": "28",
    "name": "Chromatic Foam",
    "echoCount": 9,
    "effects": [
      {
        "pieces": 2,
        "description": "Fusion DMG + 10%"
      },
      {
        "pieces": 5,
        "description": "When the Resonator inflicts Fusion Burst on the enemies, they gain the following effects: Gain 10% Fusion DMG Bonus for 15 s. While this effect is active, casting an Outro Skill grants the incoming Resonator 25% Fusion DMG Bonus for 15s."
      }
    ]
  },
  {
    "id": "29",
    "name": "Sound of True Name",
    "echoCount": 8,
    "effects": [
      {
        "pieces": 2,
        "description": "Aero DMG + 10%"
      },
      {
        "pieces": 5,
        "description": "Dealing Echo Skill DMG to enemies increases the Resonator's Echo Skill Crit. Rate by 20%, and grants 15% Aero DMG Bonus for 5s."
      }
    ]
  },
  {
    "id": "30",
    "name": "Wishes of Quiet Snowfall",
    "echoCount": 8,
    "effects": [
      {
        "pieces": 2,
        "description": "Glacio DMG + 10%"
      },
      {
        "pieces": 5,
        "description": "Inflicting Glacio Chafe on enemies increases Glacio DMG dealt by 10% for 15s. The Resonator gains the Snowfall effect for 15s, which can be triggered once every 25s. While Snowfall is active:\n- Dealing Resonance Liberation DMG removes Snowfall and increases the Resonator's Crit. Rate by 25% for 6s. While the effect is active, dealing Resonance Liberation DMG extends its duration by 4s, triggered once every 0.5s, up to 6 times.\n- Casting Outro Skill removes Snowfall and grants 25% Glacio DMG Bonus to the incoming Resonator for 15s.\nWhen Snowfall is removed, only one of the effects above can be triggered."
      }
    ]
  },
  {
    "id": "31",
    "name": "Reel of Spliced Memories",
    "echoCount": 8,
    "effects": [
      {
        "pieces": 2,
        "description": "ATK + 10%"
      },
      {
        "pieces": 5,
        "description": "Inflicting Tune Rupture - Shifting or Tune Strain - Shifting on enemies increases the Tune Break Boost of Resonators in the team by 20 for 30s. Effects of the same name do not stack."
      }
    ]
  },
  {
    "id": "32",
    "name": "Shadow of Shattered Dreams",
    "echoCount": 1,
    "effects": [
      {
        "pieces": 1,
        "description": "Inflicting Hack - Shifting on the target grants 35% Basic Attack DMG Bonus and Heavy Attack DMG Bonus for 15s."
      }
    ]
  },
  {
    "id": "33",
    "name": "Song of Feathered Trace",
    "echoCount": 8,
    "effects": [
      {
        "pieces": 2,
        "description": "Energy Regen + 10%"
      },
      {
        "pieces": 5,
        "description": "Upon inflicting Havoc Bane, gain Xuanling's Feather, which grants a 20% increase in Crit. Rate and 35% increase in Heavy Attack DMG Bonus to the Resonator, lasting 15s.\nUpon inflicting Glacio Chafe, gain Chongming's Feather, which grants a 0.1% increase in ATK to Resonators in the team for every 1% of the Resonator's Energy Regen, up to 25%, lasting 10s."
      }
    ]
  },
  {
    "id": "34",
    "name": "Heart of Evil's Purge",
    "echoCount": 7,
    "effects": [
      {
        "pieces": 2,
        "description": "Aero DMG + 10%"
      },
      {
        "pieces": 5,
        "description": "Inflicting Tune Strain - Shifting increases Crit. DMG by 20% and Aero DMG Bonus 30% for 15s."
      }
    ]
  },
  {
    "id": "35",
    "name": "Lamp of Nether Road",
    "echoCount": 7,
    "effects": [
      {
        "pieces": 2,
        "description": "HP + 10%"
      },
      {
        "pieces": 5,
        "description": "Upon gaining a Shield, gain 5% increase in Crit. Rate for 5s, max 4 stacks. This effect can be triggered every 0.5s. At max stacks, gain 15% Fusion DMG Bonus."
      }
    ]
  }
]
export const generatedSonataIconSources:Record<string,string>={
  "Freezing Frost": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriIce.webp",
  "Molten Rift": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriFire.webp",
  "Void Thunder": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriThunder.webp",
  "Sierra Gale": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriWind.webp",
  "Celestial Light": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriLight.webp",
  "Havoc Eclipse": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriDark.webp",
  "Rejuvenating Glow": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriCure.webp",
  "Moonlit Clouds": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriCloud.webp",
  "Lingering Tunes": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriAttack.webp",
  "Frosty Resolve": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriIceUltimateSkill.webp",
  "Eternal Radiance": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriLightError.webp",
  "Midnight Veil": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriDarkAssist.webp",
  "Empyrean Anthem": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriCooperate.webp",
  "Tidebreaking Courage": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriEnergy.webp",
  "Gusts of Welkin": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriWindError.webp",
  "Windward Pilgrimage": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriWindErrorA.webp",
  "Flaming Clawprint": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriFireUltimateSkill.webp",
  "Dream of the Lost": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriDarkVision.webp",
  "Crown of Valor": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriShield.webp",
  "Law of Harmony": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriSupport.webp",
  "Flamewing's Shadow": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriFireA.webp",
  "Thread of Severed Fate": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriQianXiao.webp",
  "Pact of Neonlight Leap": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriLightWeakness.webp",
  "Halo of Starry Radiance": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriCureWeakness.webp",
  "Rite of Gilded Revelation": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriAttackWeakness.webp",
  "Trailblazing Star": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriFireA1.webp",
  "Chromatic Foam": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriFireA2.webp",
  "Sound of True Name": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriWindVision.webp",
  "Wishes of Quiet Snowfall": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriIceA1.webp",
  "Reel of Spliced Memories": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriSupport1.webp",
  "Shadow of Shattered Dreams": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriAdam.webp",
  "Song of Feathered Trace": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriYangyang.webp",
  "Heart of Evil's Purge": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriQingxiao.webp",
  "Lamp of Nether Road": "https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconElementAttri/T_IconElementAttriJingran.webp"
}
