import { calculateRotation, formatDamage } from '../domain/damage'
import { resonators, weapons } from '../game-data'
import { db } from '../storage/database'
import type { BuffEffect, Build, Echo, RotationAction, Team } from '../domain/types'
import { Icon, PageHeader, Panel } from './components'

export function TeamsView({ echoes, builds, teams, refresh }: { echoes: Echo[]; builds: Build[]; teams: Team[]; refresh: () => Promise<void> }) {
  const team = teams[0]
  if (!team) return <><PageHeader eyebrow="Team roster" title="Teams" description="Connect owned characters into three-member teams."/><Panel className="empty-state"><div className="empty-glyph">03</div><h2>No team has been created yet</h2><p>Team creation will use the owned characters and their saved loadouts.</p></Panel></>
  const rotation = calculateRotation(team, builds, resonators, weapons, echoes)
  const update = async (patch: Partial<Team>) => { await db.teams.update(team.id, patch); await refresh() }
  const updateAction = async (id: string, patch: Partial<RotationAction>) => update({ actions: team.actions.map((action) => action.id === id ? { ...action, ...patch } : action) })
  const addAction = async () => {
    const build = builds.find((item) => team.buildIds.includes(item.id))
    const resonator = resonators.find((item) => item.id === build?.resonatorId)
    if (!build || !resonator) return
    await update({ actions: [...team.actions, { id: crypto.randomUUID(), timestamp: Math.min(team.rotationDuration, Math.ceil((team.actions.at(-1)?.timestamp ?? 0) + 1)), buildId: build.id, attackId: resonator.attacks[0].id }] })
  }
  const updateBuff = async (id: string, patch: Partial<BuffEffect>) => update({ buffs: (team.buffs ?? []).map((buff) => buff.id === id ? { ...buff, ...patch } : buff) })
  const addBuff = async () => {
    const build = builds.find((item) => team.buildIds.includes(item.id))
    const resonator = resonators.find((item) => item.id === build?.resonatorId)
    if (!build || !resonator) return
    await update({ buffs: [...(team.buffs ?? []), { id: crypto.randomUUID(), name: 'Team modifier', sourceBuildId: build.id, target: 'team', triggerAttackId: resonator.attacks[0].id, duration: 10, stat: 'atkPercent', value: 10, stackingGroup: `custom-${crypto.randomUUID()}` }] })
  }
  return <>
    <PageHeader eyebrow="Rotation room" title="Team damage timeline" description="Sequence real actions against a configured target and see exactly where expected damage comes from." />
    <div className="team-config"><Panel><label>Enemy level<input type="number" min="1" max="200" value={team.enemy.level} onChange={(event) => update({ enemy: { ...team.enemy, level: Math.min(200, Math.max(1, Number(event.target.value))) } })}/></label><label>Resistance %<input type="number" min="-100" max="100" value={team.enemy.resistance} onChange={(event) => update({ enemy: { ...team.enemy, resistance: Math.min(100, Math.max(-100, Number(event.target.value))) } })}/></label><label>Rotation seconds<input type="number" min="1" max="600" value={team.rotationDuration} onChange={(event) => update({ rotationDuration: Math.min(600, Math.max(1, Number(event.target.value))) })}/></label></Panel><Panel className="rotation-total"><span>EXPECTED ROTATION</span><strong>{formatDamage(rotation.total)}</strong><small>{formatDamage(rotation.dps)} damage / second</small></Panel></div>
    <div className="team-grid"><Panel><div className="section-heading"><div><span className="eyebrow">Three-member field unit</span><h2>{team.name}</h2></div></div><div className="team-members">{team.buildIds.map((id, index) => { const build = builds.find((item) => item.id === id); const resonator = resonators.find((item) => item.id === build?.resonatorId); const contribution = rotation.byBuild[id] ?? 0; return <article key={id} style={{ '--accent': resonator?.accent } as React.CSSProperties}><span>0{index + 1}</span><div className="avatar">{resonator?.name[0]}</div><h3>{resonator?.name}</h3><p>{resonator?.role}</p><strong>{formatDamage(contribution)}</strong><small>{rotation.total ? Math.round(contribution / rotation.total * 100) : 0}% contribution</small></article> })}</div></Panel><Panel><div className="section-heading"><div><span className="eyebrow">Ordered actions</span><h2>{team.rotationDuration}s timeline</h2></div></div><div className="timeline">{rotation.actions.map((action, index) => { const build = builds.find((item) => item.id === action.buildId); const resonator = resonators.find((item) => item.id === build?.resonatorId); const attack = resonator?.attacks.find((item) => item.id === action.attackId); return <div key={`${action.buildId}-${index}`}><time>{action.timestamp.toFixed(1)}s</time><i style={{ '--accent': resonator?.accent } as React.CSSProperties}/><span><strong>{resonator?.name}</strong><small>{attack?.name}</small></span><b>{formatDamage(action.expected)}</b></div> })}</div></Panel></div>
    <div className="rotation-editors"><Panel><div className="section-heading"><div><span className="eyebrow">Rotation authoring</span><h2>Actions</h2></div><button className="secondary" onClick={addAction}><Icon name="plus"/>Add action</button></div><div className="action-editor-list">{[...team.actions].sort((left, right) => left.timestamp - right.timestamp).map((action) => { const actionBuild = builds.find((item) => item.id === action.buildId); const actionResonator = resonators.find((item) => item.id === actionBuild?.resonatorId); return <div className="action-editor" key={action.id}><input aria-label="Timestamp" type="number" min="0" max={team.rotationDuration} step="0.1" value={action.timestamp} onChange={(event) => updateAction(action.id, { timestamp: Number(event.target.value) })}/><select aria-label="Character" value={action.buildId} onChange={(event) => { const nextBuild = builds.find((item) => item.id === event.target.value); const nextResonator = resonators.find((item) => item.id === nextBuild?.resonatorId); void updateAction(action.id, { buildId: event.target.value, attackId: nextResonator?.attacks[0].id ?? '' }) }}>{team.buildIds.map((id) => { const item = builds.find((entry) => entry.id === id); const character = resonators.find((entry) => entry.id === item?.resonatorId); return <option key={id} value={id}>{character?.name}</option> })}</select><select aria-label="Attack" value={action.attackId} onChange={(event) => updateAction(action.id, { attackId: event.target.value })}>{actionResonator?.attacks.map((attack) => <option key={attack.id} value={attack.id}>{attack.name}</option>)}</select><button className="text-button" onClick={() => update({ actions: team.actions.filter((item) => item.id !== action.id) })}>Remove</button></div> })}</div></Panel>
      <Panel><div className="section-heading"><div><span className="eyebrow">Declarative effects</span><h2>Buffs</h2></div><button className="secondary" onClick={addBuff}><Icon name="plus"/>Add buff</button></div><div className="buff-editor-list">{(team.buffs ?? []).map((buff) => { const sourceBuild = builds.find((item) => item.id === buff.sourceBuildId); const sourceResonator = resonators.find((item) => item.id === sourceBuild?.resonatorId); return <div className="buff-editor" key={buff.id}><input aria-label="Buff name" value={buff.name} onChange={(event) => updateBuff(buff.id, { name: event.target.value })}/><select aria-label="Source" value={buff.sourceBuildId} onChange={(event) => { const nextBuild = builds.find((item) => item.id === event.target.value); const nextResonator = resonators.find((item) => item.id === nextBuild?.resonatorId); void updateBuff(buff.id, { sourceBuildId: event.target.value, triggerAttackId: nextResonator?.attacks[0].id ?? '' }) }}>{team.buildIds.map((id) => { const item = builds.find((entry) => entry.id === id); const character = resonators.find((entry) => entry.id === item?.resonatorId); return <option key={id} value={id}>{character?.name}</option> })}</select><select aria-label="Trigger" value={buff.triggerAttackId} onChange={(event) => updateBuff(buff.id, { triggerAttackId: event.target.value })}>{sourceResonator?.attacks.map((attack) => <option key={attack.id} value={attack.id}>{attack.name}</option>)}</select><select aria-label="Target" value={buff.target} onChange={(event) => updateBuff(buff.id, { target: event.target.value as BuffEffect['target'] })}><option value="self">Self</option><option value="next">Next character</option><option value="team">Team</option></select><select aria-label="Modifier" value={buff.stat} onChange={(event) => updateBuff(buff.id, { stat: event.target.value as BuffEffect['stat'] })}><option value="atkPercent">ATK %</option><option value="hpPercent">HP %</option><option value="critRate">Crit. Rate</option><option value="critDamage">Crit. DMG</option><option value="skillDamage">Skill DMG</option><option value="liberationDamage">Liberation DMG</option><option value="amplify">Amplify</option></select><input aria-label="Value" type="number" step="0.1" value={buff.value} onChange={(event) => updateBuff(buff.id, { value: Number(event.target.value) })}/><input aria-label="Duration" type="number" min="0" step="0.1" value={buff.duration} onChange={(event) => updateBuff(buff.id, { duration: Number(event.target.value) })}/><button className="text-button" onClick={() => update({ buffs: (team.buffs ?? []).filter((item) => item.id !== buff.id) })}>Remove</button></div> })}{!(team.buffs ?? []).length && <p className="muted-copy">No custom buffs. Add one to model an Outro, passive, or team effect.</p>}</div></Panel></div>
    <Panel><div className="section-heading"><div><span className="eyebrow">Damage distribution</span><h2>By attack type</h2></div></div><div className="breakdown">{Object.entries(rotation.byType).map(([type, value]) => <div key={type}><span>{type}</span><div><i style={{ width: `${rotation.total ? value / rotation.total * 100 : 0}%` }}/></div><strong>{formatDamage(value)}</strong></div>)}</div></Panel>
  </>
}
